name: CI - Train and Dockerize Model

on:
  push:
    branches:
      - main

jobs:
  train-and-dockerize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install mlflow scikit-learn pandas numpy dagshub

      - name: Run MLflow Project
        run: |
          cd MLProject
          mlflow run . --env-manager=local

      - name: Build Docker Image with MLflow
        run: |
          cd MLProject
          mlflow models build-docker -m runs:/$(ls -t mlruns/0 | head -1)/artifacts/model -n fazima/sml_submission:latest

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Push Docker Image
        run: |
          docker push fazima/sml_submission:latest
