name: name: crop-recommendation
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - scikit-learn
  - mlflow
  - pip
  - pip:
      - dagshub
      - fastapi
      - uvicorn
      - scikit-learn
      - joblib
      - pandas
      - numpy
      - mlflow==2.19.0
